#31

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,13 +34,17 @@ jobs:
           echo "$SSH_PRIVATE_KEY" | sed 's/\r$//' > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
+      - name: Add known hosts
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan -H 172.27.8.165 >> ~/.ssh/known_hosts
+
       - name: Test SSH connection
         run: ssh -v -o StrictHostKeyChecking=no daeun@172.27.8.165 'echo "SSH connection successful"'
-
-      - name: Attempt SSH key scan
-        run: |
-          set -x  # Enable debugging
-          ssh-keyscan -v -H 172.27.8.165 || echo "ssh-keyscan failed"
+#      - name: Attempt SSH key scan
+#        run: |
+#          set -x  # Enable debugging
+#          ssh-keyscan -v -H 172.27.8.165 || echo "ssh-keyscan failed"
       #      - name: Set up SSH key
       #        env:
       #          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
